sudo dnf install plasma-desktop
sudo dnf install plasma-workspace
sudo dnf install qt5-qtbase-gui
sudo dnf install sddm
sudo dnf install sddm-breeze
sudo dnf install sddm-kcm
sudo dnf install NetworkManager-config-connectivity-fedora
sudo dnf install PackageKit-command-not-found
sudo dnf install abrt-desktop
sudo dnf install adwaita-gtk2-theme
sudo dnf install bluedevil
sudo dnf install breeze-icon-theme
sudo dnf install colord-kde
sudo dnf install cups-pk-helper
sudo dnf install dnfdragora
sudo dnf install dolphin
sudo dnf install firewall-config 
glibc-all-langpacks
sudo dnf install gnome-keyring-pam
sudo dnf install gwenview
sudo dnf install initial-setup-gui
sudo dnf install kamera
sudo dnf install kcalc
sudo dnf install kcharselect
sudo dnf install kde-gtk-config
sudo dnf install kde-partitionmanager
sudo dnf install kde-print-manager
sudo dnf install kde-settings-pulseaudio
sudo dnf install kdegraphics-thumbnailers
sudo dnf install kdeplasma-addons
sudo dnf install kdialog
sudo dnf install kdnssd
sudo dnf install keditbookmarks
sudo dnf install kf5-akonadi-server
sudo dnf install kf5-akonadi-server-mysql
sudo dnf install kf5-baloo-file
sudo dnf install kf5-kipi-plugins
sudo dnf install khelpcenter
sudo dnf install khotkeys
sudo dnf install kinfocenter
sudo dnf install kmenuedit
sudo dnf install konsole5
sudo dnf install kscreen
sudo dnf install kscreenlocker
sudo dnf install ksshaskpass
sudo dnf install kwebkitpart
sudo dnf install kwin
sudo dnf install kwrite
sudo dnf install okular
sudo dnf install phonon-qt5-backend-gstreamer
sudo dnf install pinentry-qt
sudo dnf install plasma-breeze
sudo dnf install plasma-desktop-doc
sudo dnf install plasma-discover
sudo dnf install plasma-discover-notifier
sudo dnf install plasma-disks
sudo dnf install plasma-drkonqi
sudo dnf install plasma-nm
sudo dnf install plasma-nm-l2tp
sudo dnf install plasma-nm-openconnect
sudo dnf install plasma-nm-openswan
sudo dnf install plasma-nm-openvpn
sudo dnf install plasma-nm-pptp
sudo dnf install plasma-nm-vpnc
sudo dnf install plasma-pa
sudo dnf install plasma-systemmonitor
sudo dnf install plasma-thunderbolt
sudo dnf install plasma-vault
sudo dnf install plasma-workspace-geolocation
sudo dnf install plasma-workspace-xorg
sudo dnf install polkit-kde
sudo dnf install qt5-qtdeclarative
sudo dnf install spectacle
sudo dnf install xdg-desktop-portal-gnome
sudo dnf install xorg-x11-drv-libinput
