sudo dnf install  plasma-desktop \
    plasma-workspace \
    qt5-qtbase-gui \
    sddm \
    sddm-breeze \
    sddm-kcm \
    NetworkManager-config-connectivity-fedora \
    PackageKit-command-not-found \
    abrt-desktop \
    adwaita-gtk2-theme \
    bluedevil \
    breeze-icon-theme \
    colord-kde \
    cups-pk-helper \
    dnfdragora \
    dolphin \
    firewall-config \
    glibc-all-langpacks \
    gnome-keyring-pam \
    gwenview \
    initial-setup-gui \
    kamera \
    kcalc \
    kcharselect \
    kde-gtk-config \
    kde-partitionmanager \
    kde-print-manager \
    kde-settings-pulseaudio \
    kdegraphics-thumbnailers \
    kdeplasma-addons \
    kdialog \
    kdnssd \
    keditbookmarks \
    kf5-akonadi-server \
    kf5-akonadi-server-mysql \
    kf5-baloo-file \
    kf5-kipi-plugins \
    khelpcenter \
    khotkeys \
    kinfocenter \
    kmenuedit \
    konsole5 \
    kscreen \
    kscreenlocker \
    ksshaskpass \
    kwebkitpart \
    kwin \
    kwrite \
    okular \
    phonon-qt5-backend-gstreamer \
    pinentry-qt \
    plasma-breeze \
    plasma-desktop-doc \
    plasma-discover \
    plasma-discover-notifier \
    plasma-disks \
    plasma-drkonqi \
    plasma-nm \
    plasma-nm-l2tp \
    plasma-nm-openconnect \
    plasma-nm-openswan \
    plasma-nm-openvpn \
    plasma-nm-pptp \
    plasma-nm-vpnc \
    plasma-pa \
    plasma-systemmonitor \
    plasma-thunderbolt \
    plasma-vault \
    plasma-workspace-geolocation \
    plasma-workspace-xorg \
    polkit-kde \
    qt5-qtdeclarative \
    spectacle \
    xdg-desktop-portal-gnome \
    xorg-x11-drv-libinput -y
